import type { Metadata } from "next";

import Header from "@/src/views/layout/Header";

import "@/src/assets/css/globals.css"

import Footer from "@/src/views/layout/Footer";
import TopButton from "@/src/components/TopButton";
import Loader from "@/src/components/Loader";
import Tawk from "@/src/components/tawk";
import CustomCursor from "@/src/components/CustomCursor";
import Clarity from "@/src/components/Clarity";
import Analytics from "@/src/components/Analytics";

export const metadata: Metadata = {
  title: "eByteLogic",
  description: "Generated by eByteLogic",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    //  <html lang="en" className={poppins.variable}>
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Loader>
          <Header />
          <main className="relative">  <CustomCursor />{children}</main>
          <Footer />
          <TopButton />
          <Clarity />
          <Analytics />
          <Tawk />
        </Loader>
      </body>
    </html>
  );
}
